from os import PathLike
from typing import Any

class DeferredValue:
    def __init__(self) -> None: ...

class NoValue:
    def __init__(self) -> None: ...

class TcRuntime:
    def __init__(
        self,
        model: str | PathLike[str],
        *,
        semantics: str = "typed-untimed",
    ) -> None: ...
    @staticmethod
    def from_text(model: str, semantics: str | None = None) -> TcRuntime: ...
    @staticmethod
    def from_path(
        path: str | PathLike[str], semantics: str | None = None
    ) -> TcRuntime: ...
    def is_initialized(self) -> bool: ...
    def step(self) -> bool: ...
    def provide_inputs(
        self, inputs: dict[str, Any] | None = None, **kwargs: Any
    ) -> None: ...
    def next_output(self, timeout: float | None = None) -> dict[str, Any] | None: ...
    def run(self) -> list[dict[str, Any]]: ...
