//! Contiguous postorder storage for occurrence trees.
//!
//! Nodes are allocated after their children, so every subtree occupies one
//! contiguous range of IDs. This makes [`TreeCursorExt::postorder`] and
//! [`TreeCursorExt::fold`] linear scans over storage. Use
//! [`TreeCursorExt::children`] for direct children and
//! [`TreeCursorExt::try_zip_with`] for structural comparison.
//!
//! [`Arena`] and [`TreeNode`] are the low-level storage interface, and
//! [`ForestBuilder`] is the invariant-preserving generic construction API.
//! [`TreeHandle`] owns one selected root, while [`Forest`] owns a validated ordered
//! set of roots sharing one storage allocation. Most typed trees are declared with
//! [`tree_schema!`] and inspected through a copyable [`TreeCursor`].
//!
//! # Representation invariants
//!
//! Child subtrees must be allocated before their parent, adjacent to one
//! another, and in source order. A node ID represents one occurrence and cannot
//! be shared by multiple parents; multiple independent roots may share storage.
//!
//! # Example
//!
//! ```
//! use contiguous_tree::{TreeCursorExt, tree_schema};
//! use ecow::EcoVec;
//!
//! tree_schema! {
//!     pub tree Term {
//!         schema: pub(crate),
//!         metadata: offset: u32 = 0,
//!         id: u32,
//!         key: String,
//!         children: EcoVec,
//!         keyed_children: EcoVec,
//!
//!         Number(value: data(i64)),
//!         Add(left: child, right: child),
//!     }
//! }
//!
//! let mut builder = TermBuilder::with_capacity(3);
//! let left = builder.alloc_default(TermKind::Number(1));
//! let right = builder.alloc_default(TermKind::Number(2));
//! let root = builder.alloc_default(TermKind::Add(left, right));
//! let term = builder.finish(root).unwrap();
//!
//! assert_eq!(term.as_ref().postorder().count(), 3);
//! ```

extern crate self as contiguous_tree;

mod annotations;
mod arena;
mod builder;
mod cursor;
mod fields;
mod forest;
mod forest_map;
mod index;
mod node;
mod storage;
mod transform;
mod traversal;

pub use annotations::{AnnotationError, NodeAnnotations, NodeAnnotationsBuilder};
pub use arena::{Arena, ForestError};
pub use builder::{BuildError, ForestBuilder};
pub use cursor::{ContextCursor, StorageIdentity, TreeCursor};
pub use fields::{KeyedFields, ResolvedFields, ResolvedIds};
pub use forest::{Forest, ForestHandles, TreeHandle};
pub use forest_map::{ForestMap, ForestMapError};
pub use index::{ArenaId, IdRange};
pub use node::{TreeNode, TreeNodeMut};
pub use storage::{PostorderStorage, TreeStorage};
pub use transform::CloneTreeError;
pub use traversal::{Children, FoldNode, Postorder, TreeCursorExt, fold, try_fold, try_zip_with};

pub use contiguous_tree_macros::{TreeCursor, tree_schema};

/// Implementation details used by code generated by [`tree_schema!`].
#[doc(hidden)]
pub mod __private {
    use crate::{Arena, ArenaId, TreeNode};

    pub use crate::node::ChildIds;
    #[cfg(feature = "serde")]
    pub use serde;

    /// Append one node for generated storage implementations.
    pub fn arena_push_node<Id: ArenaId, Node: TreeNode<Id>>(
        arena: &mut Arena<Id, Node>,
        node: Node,
    ) -> Id {
        arena.push_tree(node)
    }

    /// Roll generated storage back to a previous node count.
    pub fn arena_truncate<Id: ArenaId, Node>(arena: &mut Arena<Id, Node>, len: usize) {
        arena.truncate(len);
    }
}

#[cfg(test)]
mod tests;
