pub mod operators;
pub use operators::*;
pub mod variables;
pub use variables::*;
pub mod interfaces;
pub use interfaces::*;
mod batch;
pub mod input;
pub(crate) mod json;
pub use input::*;
mod layout;
pub(crate) use layout::ValidatedLayout;
mod partial_value;
pub(crate) use partial_value::{PartialMarker, propagated_special, retain_last, retain_stream};
pub mod output;
pub use output::*;
pub mod values;
pub use values::*;
pub mod stream_casting;
pub use stream_casting::*;

pub const MQTT_HOSTNAME: &str = "localhost";
pub const REDIS_HOSTNAME: &str = "localhost";
